def gv

pipeline {
    agent any
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    echo "building jar"
                    //gv.buildJar()
                }
            }
        }
        stage("build image") {
            steps {
                script {
                    echo "building image"
                    //gv.buildImage()
                }
            }
        }
        stage("deploy") {
            steps {
                script {
                    echo "deploying"
                    //gv.deployApp()
                }
            }
        }
    }
}

// https://techworld-with-nana.teachable.com/courses/devops-bootcamp/lectures/28665213 - Jenkinsfile Syntax
// https://gitlab.com/JavaScriptonit/java-maven-app/-/edit/master/Jenkinsfile - Example of Jenkins file